# Generated by Django 5.2.5 on 2025-08-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tifo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tifo date')),
                ('tifo_type', models.CharField(choices=[('C', 'Choreo'), ('P', 'Pyro Show'), ('B', 'Banner')], default='C', max_length=1)),
                ('description', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
