# Generated by Django 5.2.5 on 2025-08-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tifo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tifo',
            name='tifo_type',
        ),
        migrations.AddField(
            model_name='tifo',
            name='match',
            field=models.CharField(default='Unknown Match', max_length=200),
        ),
        migrations.AddField(
            model_name='tifo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tifos/'),
        ),
    ]
