# Generated by Django 5.2.5 on 2025-08-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tifo_tifo_type_tifo_match_tifo_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tifo',
            name='tifo_type',
            field=models.CharField(choices=[('C', 'Choreo'), ('P', 'Pyro Show'), ('B', 'Banner')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='tifo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tifo',
            name='match',
            field=models.CharField(default='Unknown match', max_length=200),
        ),
    ]
