# Generated by Django 5.2.5 on 2025-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_country_alter_group_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='group_logos/'),
        ),
    ]
